### ISSUE TITLE
job pod succeeds, but worker registeres a FATAL error

### ISSUE THREAD

**Issue by omgjlk** [Azure/brigade#186] opened 2017-11-30 19:26 UTC
I've got a simple job setup:
```
const { events, Job } = require('brigadier')

events.on("push", (brigadeEvent, project) => {
    var job = new Job("demojob", "alpine:3.4")
    job.env = {
        "leakme": project.secrets.leakme
    }
    job.tasks = [
        "echo Line 1",
        "echo Line 2",
        "echo $leakme"
    ]

    job.run()
})

events.on("pull_request", (brigadeEvent, project) => {
    var job = new Job("pulljob", "alpine:3.4")
    job.env = {
        "leakme": project.secrets.leakme
    }
    job.tasks = [
        "echo Line 1",
        "echo Line 2",
        "echo $leakme"
    ]

    job.run()
})
```

When a pull request job comes in, I can see the worker pod fire off, and the logs show something interesting:
```
> kubectl logs brigade-worker-01c07578kfq4gk6gf9nt8aredx-11426f2c
yarn run v1.3.2
$ node prestart.js
prestart: src/brigade.js written
$ node --no-deprecation ./dist/src/index.js
Creating PVC named brigade-worker-01c07578kfq4gk6gf9nt8aredx-11426f2c
looking up default/github-com-j2sol-demobrigade-pulljob
Creating secret pulljob-1512068853475-11426f2c
Creating Job Cache PVC github-com-j2sol-demobrigade-pulljob
undefined
Creating pod pulljob-1512068853475-11426f2c
Timeout set at 900000
default/pulljob-1512068853475-11426f2c phase Pending
default/pulljob-1512068853475-11426f2c phase Pending
default/pulljob-1512068853475-11426f2c phase Succeeded
FATAL: job pulljob(pulljob-1512068853475-11426f2c): [object Object] (rejection)
error handler is cleaning up
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The pulljob pod appears to be successful, but gets marked as fatal?

Here's the log from pulljob:

```
> kubectl describe pod pulljob-1512068853475-11426f2c
Name:		pulljob-1512068853475-11426f2c
Namespace:	default
Node:		10.184.120.199/10.184.120.199
Start Time:	Thu, 30 Nov 2017 11:07:33 -0800
Labels:		build=01c07578kfq4gk6gf9nt8aredx
		commit=11426f2c689a6a7ccb78a6c6e366ce040e5f797d
		component=job
		heritage=brigade
		jobname=pulljob
		project=brigade-463662f2bc06a89c2464d52d1b248602a1085ed2ccf2953df6a8fa
		worker=brigade-worker-01c07578kfq4gk6gf9nt8aredx-11426f2c
Annotations:	<none>
Status:		Succeeded
IP:		172.30.13.15
Init Containers:
  brigade-vcs-sidecar:
    Container ID:	docker://7fe43d4a2133b673ed88d5e960a2a24a440d58d9bd79a20cf015bc9812396246
    Image:		iamjlk/git-sidecar:jlk
    Image ID:		docker-pullable://iamjlk/git-sidecar@sha256:39515695d5c0582e13aa603220976244196dd43c4053ca7554c9029047821ab3
    Port:		<none>
    State:		Terminated
      Reason:		Completed
      Exit Code:	0
      Started:		Thu, 30 Nov 2017 11:07:35 -0800
      Finished:		Thu, 30 Nov 2017 11:07:36 -0800
    Ready:		True
    Restart Count:	0
    Environment:
      VCS_REPO:		https://github.com/j2sol/demobrigade.git
      VCS_LOCAL_PATH:	/src
      VCS_REVISION:	11426f2c689a6a7ccb78a6c6e366ce040e5f797d
      VCS_AUTH_TOKEN:	<hidden>
    Mounts:
      /src from vcs-sidecar (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from brigade-worker-token-4dbns (ro)
Containers:
  brigaderun:
    Container ID:	docker://c6fb7791eb9a5f3819e9757b5e9d220e1f906b2065dbb1204840760f0dec2324
    Image:		alpine:3.4
    Image ID:		docker-pullable://alpine@sha256:915b0ffca1d76ac57d83f28d568bcb516b6c274843ea8df7fac4b247440f796b
    Port:		<none>
    Command:
      /bin/sh
      /hook/main.sh
    State:		Terminated
      Reason:		Completed
      Exit Code:	0
      Started:		Thu, 30 Nov 2017 11:07:37 -0800
      Finished:		Thu, 30 Nov 2017 11:07:38 -0800
    Ready:		False
    Restart Count:	0
    Environment:
      leakme:		<set to the key 'leakme' in secret 'pulljob-1512068853475-11426f2c'>	Optional: false
      CLONE_URL:	https://github.com/j2sol/demobrigade.git
      HEAD_COMMIT_ID:	11426f2c689a6a7ccb78a6c6e366ce040e5f797d
      CI:		true
    Mounts:
      /hook from pulljob-1512068853475-11426f2c (rw)
      /src from vcs-sidecar (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from brigade-worker-token-4dbns (ro)
Conditions:
  Type		Status
  Initialized 	True
  Ready 	False
  PodScheduled 	True
Volumes:
  pulljob-1512068853475-11426f2c:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	pulljob-1512068853475-11426f2c
    Optional:	false
  vcs-sidecar:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  brigade-worker-token-4dbns:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	brigade-worker-token-4dbns
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	node.alpha.kubernetes.io/notReady:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath					Type		ReasonMessage
  ---------	--------	-----	----			-------------					--------	-------------
  45s		45s		1	default-scheduler							Normal		Scheduled		Successfully assigned pulljob-1512068853475-11426f2c to 10.184.120.199
  45s		45s		1	kubelet, 10.184.120.199							Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "vcs-sidecar"
  45s		45s		1	kubelet, 10.184.120.199							Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "brigade-worker-token-4dbns"
  45s		45s		1	kubelet, 10.184.120.199							Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "pulljob-1512068853475-11426f2c"
  43s		43s		1	kubelet, 10.184.120.199	spec.initContainers{brigade-vcs-sidecar}	Normal		PulledContainer image "iamjlk/git-sidecar:jlk" already present on machine
  43s		43s		1	kubelet, 10.184.120.199	spec.initContainers{brigade-vcs-sidecar}	Normal		Created			Created container
  43s		43s		1	kubelet, 10.184.120.199	spec.initContainers{brigade-vcs-sidecar}	Normal		Started			Started container
  41s		41s		1	kubelet, 10.184.120.199	spec.containers{brigaderun}			Normal		PulledContainer image "alpine:3.4" already present on machine
  41s		41s		1	kubelet, 10.184.120.199	spec.containers{brigaderun}			Normal		Created			Created container
  41s		41s		1	kubelet, 10.184.120.199	spec.containers{brigaderun}			Normal		Started			Started container

> kubectl logs pulljob-1512068853475-11426f2c -c brigade-vcs-sidecar
+ : /src
+ : https://github.com/j2sol/demobrigade.git
+ : 11426f2c689a6a7ccb78a6c6e366ce040e5f797d
+ git clone --depth=50 https://github.com/j2sol/demobrigade.git /src
Cloning into '/src'...
+ cd /src
+ git fetch origin 11426f2c689a6a7ccb78a6c6e366ce040e5f797d
From https://github.com/j2sol/demobrigade
 * branch            11426f2c689a6a7ccb78a6c6e366ce040e5f797d -> FETCH_HEAD
+ git checkout -qf FETCH_HEAD
+ git reset --hard -q 11426f2c689a6a7ccb78a6c6e366ce040e5f797d

> kubectl logs pulljob-1512068853475-11426f2c -c brigaderun
Line 1
Line 2
I am not a crook
```

I can't see where this error is coming from. Any help?

**Comment by technosophos** [comment] 2017-12-01 00:12
All I can figure is that something about the last `echo` is not returning 0. But I don't see why that would be.

**Comment by technosophos** [comment] 2017-12-01 00:14
And the thing you are testing there is something we're looking into. We'd like to obfuscate or redact secrets that are leaked into the logs.

**Comment by cordoval** [comment] 2017-12-01 01:47
is this related to the comment i did for arguments of a function in a previous merged PR? just saying

**Comment by bacongobbler** [comment] 2017-12-01 03:23
Are you referring to https://github.com/Azure/brigade/pull/178? If so no, that’s different.

**Comment by blimmer** [comment] 2017-12-22 22:20
I am experiencing this same problem. With this Brigade file:

```js
const { events, Job } = require('brigadier')

events.on('image_push', (e) => {
  let payload = JSON.parse(e.payload);

  let job = new Job(
    "deploy-k8s-demo",
    "<myawsaccountid>.dkr.ecr.us-east-1.amazonaws.com/k8s-deploy:1.1.0", [
      `<mycommand> ${payload.imageTag}`,
      `echo $?`
    ]);
  job.run().then((e) => {
    console.log(`In success: ${e.toString()}`);
  }, (e) => {
    console.log(`In failure ${e.toString()}`);
  });
});
```

and I'm getting `0` echoed out in the pod logs

```console
 The current Primary Color in use is: blue
It is taking 100% of traffic for the service
...
0 
```

but the promise is rejecting

```console
 operations/deploy-k8s-demo-1513979239919-ed2e182d phase Pending
operations/deploy-k8s-demo-1513979239919-ed2e182d phase Running
operations/deploy-k8s-demo-1513979239919-ed2e182d phase Running
operations/deploy-k8s-demo-1513979239919-ed2e182d phase Running
operations/deploy-k8s-demo-1513979239919-ed2e182d phase Running
operations/deploy-k8s-demo-1513979239919-ed2e182d phase Succeeded
In failure job deploy-k8s-demo(deploy-k8s-demo-1513979239919-ed2e182d): [object Object]
after: default event fired
beforeExit(2): destroying storage
Destroying PVC named brigade-worker-01c2033nvkp79c4n8w0xwm4p97-ed2e182d
Done in 12.66s. 
```

I can't find a way to dig more into the `[object Object]` thing either

**Comment by technosophos** [comment] 2018-01-17 21:10
Okay, we _think_ we found and fixed this error in 0.8. If anyone can confirm, that would be great.

**Comment by technosophos** [comment] 2018-01-19 00:22
I reproduced this today on an RBAC-enabled cluster, and it was happening because one permission setting was omitted.

**Closed** 2018-01-19 20:42 UTC
Labels: question

**Comment by omgjlk** [comment] 2018-01-26 02:52
I haven't tested on the k8s that supported rbac yet (that was google compute I believe). But I just tested on my laptop with docker for mac w/ k8s built in and it seems to be working!
