### ISSUE TITLE
PVC Not Bound, Can't Use Shared Storage or Cache

### ISSUE THREAD

**Issue by smm190** [Azure/brigade#347] opened 2018-03-06 16:31 UTC
I am trying to use shared storage to pass information between jobs.  It is attempting to create a PVC that gets stuck in pending state, the storage class is azurefile and it is ReadWriteMany.    The only error I see is:

PersistentVolumeClaim is not bound: "github-com-deis-empty-testbed-one" (repeated 5 times)

I am using the most recent version of brigade, v0.10.0.

**Comment by lukepatrick** [comment] 2018-03-06 17:58
Likely you will want to set up storage as described in this PR #344

**Comment by technosophos** [comment] 2018-03-06 19:30
@smm190 I have occasionally seen this issue with AzureFile, and have observed two root causes:

1. I have hit very slow AzureFile provisioning times (~10 mnutes). I am told "that will be fixed in the future". 
2. On one of my ACS clusters, I had some weird case where the token the cluster had was invalidated, and I couldn't provision a pod anymore. Perhaps @lachie83 knows how to fix this.

For testing, I set up the NFS system @lukepatrick pointed to. I have it on an AKS cluster. It is _really_ fast, and I'm thinking of using it by default from now on just because it shaves 20 to 30 seconds off of every Brigade build.

**Comment by smm190** [comment] 2018-03-06 20:57
@technosophos Do you know if nfs-provisioner can be installed on a cluster that doesn't have rbac enabled? When installing it, even with --set rbac.enabled=false, the install fails with an error "cluster-admin" not found.

Trying @lukepatrick 's suggestion..

helm install --name nfs-provisioner --namespace nfs-provisioner nfs-provisioner/nfs-provisioner --set rbac.enabled=false
Error: release nfs-provisioner failed: clusterroles.rbac.authorization.k8s.io "nfs-provisioner-runner" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["persistentvolumes"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["persistentvolumes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["persistentvolumes"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["persistentvolumes"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["persistentvolumes"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["persistentvolumeclaims"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["persistentvolumeclaims"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["persistentvolumeclaims"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["persistentvolumeclaims"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["storageclasses"], APIGroups:["storage.k8s.io"], Verbs:["get"]} PolicyRule{Resources:["storageclasses"], APIGroups:["storage.k8s.io"], Verbs:["list"]} PolicyRule{Resources:["storageclasses"], APIGroups:["storage.k8s.io"], Verbs:["watch"]} PolicyRule{Resources:["events"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["events"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["events"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["events"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["events"], APIGroups:[""], Verbs:["patch"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["podsecuritypolicies"], ResourceNames:["nfs-provisioner"], APIGroups:["extensions"], Verbs:["use"]}] user=&{system:serviceaccount:kube-system:tiller ------ [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[clusterroles.rbac.authorization.k8s.io "cluster-admin" not found]

**Comment by technosophos** [comment] 2018-03-06 23:17
Ah! I see that the upstream chart is not yet updated. Try this:

1. Clone the `nfs-provisioner-chart` repo
2. `cd` into that directory
3. Run the same Helm command, but substitute the relative path to the chart: `helm install -n nfs ./charts/nfs-provisioner # the rest of the flags...`

That will use the copy of the chart in `./charts/nfs-provisioner` instead of the one in the chart repository, which is out of date.

**Comment by smm190** [comment] 2018-03-07 18:28
Got it working.  Thank you @technosophos

**Comment by smm190** [comment] 2018-03-07 20:11
@technosophos A little bit of a backtrack here but I was initially trying install nfs-provisioner on a v1.9 cluster, which is where I ran into the problem above where "nfs-provisioner failed". I then created a new 1.8 cluster, which is where I was able to install nfs-provisioner successfully (without having to clone the repo and run the helm install with the relative path).  I am back to trying to get it to work on a 1.9 cluster, and running into the same issue as yesterday where the nfs-provisioner fails, even when cloning the repo and using the relative path in the helm install command.

I'd like to be able to use this on a 1.9 cluster.  Is there any difference you are aware of that might be causing this behavior?

**Comment by technosophos** [comment] 2018-03-07 20:17
Nothing I directly know of. And now that you mention it, both of the clusters I installed on are 1.8.

**Comment by smm190** [comment] 2018-03-27 21:15
@technosophos We still can't get nfs-provisioner installed on a 1.9 cluster, and we no longer can stay on a 1.8 cluster.  Do you have any suggestions on how we can move forward?

**Comment by elvisace** [comment] 2018-09-22 20:29
what would be the implications of using an NFS system in production?

**Comment by technosophos** [comment] 2018-09-24 15:30
It should be okay to use in production. It is a faster volume system than most of the alternatives, and since it's essentially acting like an ephemeral storage layer, the long-term reliability of any particular volume is not really an issue.

What I am not sure about is whether there are any particular security implications with using the NFS provisioner. I can honestly say that I have not looked into this at all.

**Comment by radu-matei** [comment] 2019-01-04 23:12
Closing.
Feel free to reopen if you have additional questions.

Thanks!

**Closed by radu-matei** 2019-01-04 23:12 UTC
Labels: question
