### ISSUE TITLE
yaml arrays are not supported for secrets

### ISSUE THREAD

**Issue by Strandedpirate** [Azure/brigade#470] opened 2018-05-23 04:04 UTC
I updated my brigade project to send a particular secret as an array like so:

```
project: "buildasign/designer"
...
secrets:
  environments:
    - name: dev
      serverName: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      databaseName: "xxxxxxxxxxxx"
      userName: "xxxxxxxxxx"
      password: "xxxxxxxxxxxxxxxxx"
...
```

and we get the following error from brig CLI. The build does not kick off either in k8s. I assume Go is blowing up internally before creating the worker with the same error.

```
λ brig project get buildasign/designer -n brigade
Error: json: cannot unmarshal array into Go value of type string
Usage:
  brig project get PROJECT [flags]

Global Flags:
      --kubeconfig string   The path to a KUBECONFIG file, overrides $KUBECONFIG.
  -n, --namespace string    The Kubernetes namespace for Brigade (default "default")
  -v, --verbose             Turn on verbose output

json: cannot unmarshal array into Go value of type string
```

This secrect should be JSON.stringify'd and then passed around as a string.
e.g. `environments: "[{\"name\": \"dev\", \"serverName\": \"xxx\", ...}]"`

**Comment by technosophos** [comment] 2018-05-24 19:01
I'll have to check whether there was some reason this was done by design, but it seems to be a bug.

**Comment by radu-matei** [comment] 2019-01-04 23:34
Closing this in favor of #486, which offers some more context.
Feel free to comment there, or reopen if this is actually another issue.

Thanks!

**Closed by radu-matei** 2019-01-04 23:34 UTC
Labels: bug
